import type { CategorySlug, Product, ProductAttributeValue, StockSnapshot, StockState } from "@/lib/storefront/types";

type SeedProduct = Readonly<{
  id: string;
  slug: string;
  name: string;
  category: CategorySlug;
  price: number;
  compareAtPrice?: number;
  unit: string;
  stockQty: number;
  featured?: boolean;
  organic?: boolean;
  tags: string[];
  shortDescription: string;
  longDescription: string;
  badges?: string[];
  image?: string;
  ageRestricted?: boolean;
  attributes: Readonly<Record<string, ProductAttributeValue>>;
  sku: string;
}>;

const categoryImageMap = {
  fruits: ["/assets/bananas.png"],
  vegetables: ["/assets/bananas.png"],
  confectionery: ["/assets/bread.png", "/assets/heack.png"],
  winery: ["/assets/wine.png"],
  beverages: ["/assets/lucozade.png"],
  groceries: ["/assets/heack.png"],
  deli: ["/assets/heack.png"],
  butchery: ["/assets/heack.png"],
  "dairy-eggs": ["/assets/heack.png"],
  household: ["/assets/heack.png"],
} as const;

function resolveProductImage(seed: SeedProduct, index: number) {
  const images = categoryImageMap[seed.category];
  return images[index % images.length];
}

function deriveStockState(stockQty: number): StockState {
  if (stockQty <= 0) {
    return "out_of_stock";
  }

  if (stockQty <= 5) {
    return "low_stock";
  }

  return "in_stock";
}

function createProduct(seed: SeedProduct, index: number): Product {
  const image = seed.image ?? resolveProductImage(seed, index);
  const stockState = deriveStockState(seed.stockQty);

  return {
    id: seed.id,
    slug: seed.slug,
    name: seed.name,
    category: seed.category,
    department: seed.category,
    price: seed.price,
    compareAtPrice: seed.compareAtPrice,
    unit: seed.unit,
    stockQty: seed.stockQty,
    stockQuantity: seed.stockQty,
    stockState,
    featured: seed.featured ?? false,
    organic: seed.organic ?? false,
    tags: seed.tags,
    shortDescription: seed.shortDescription,
    longDescription: seed.longDescription,
    description: seed.longDescription,
    image,
    images: [{ src: image, alt: seed.name }],
    badges: seed.badges ?? [],
    ageRestricted: seed.ageRestricted ?? false,
    attributes: seed.attributes,
    sku: seed.sku,
  };
}

const productSeeds: SeedProduct[] = [
  {
    id: "p-001",
    slug: "sunrise-orange-crate",
    name: "Sunrise Orange Crate",
    category: "fruits",
    price: 12.9,
    compareAtPrice: 14.5,
    unit: "4 kg crate",
    stockQty: 18,
    featured: true,
    organic: true,
    tags: ["citrus", "breakfast", "vitamin c", "family"],
    shortDescription: "Sweet breakfast oranges selected for juicing and lunch boxes.",
    longDescription: "A balanced citrus crate packed with sweet, easy-peel oranges that work well for juicing, office snacks, and family breakfasts.",
    badges: ["Best seller", "Organic"],
    attributes: { variety: "Valencia", packStyle: "crate", origin: "Mazowe" },
    sku: "FRT-001",
  },
  {
    id: "p-002",
    slug: "golden-mango-bundle",
    name: "Golden Mango Bundle",
    category: "fruits",
    price: 8.6,
    unit: "6 fruit pack",
    stockQty: 10,
    featured: true,
    tags: ["mango", "tropical", "smoothie", "snacking"],
    shortDescription: "Ripe mangoes chosen for smoothies, desserts, and quick snacks.",
    longDescription: "A tropical bundle of ready-to-ripen mangoes with rich sweetness for smoothies, fruit bowls, and chilled dessert plates.",
    badges: ["Seasonal"],
    attributes: { variety: "Tommy Atkins", ripeness: "ready to ripen", count: 6 },
    sku: "FRT-002",
  },
  {
    id: "p-003",
    slug: "ruby-grapefruit-pair",
    name: "Ruby Grapefruit Pair",
    category: "fruits",
    price: 3.8,
    unit: "2 fruit pack",
    stockQty: 14,
    organic: true,
    tags: ["grapefruit", "citrus", "breakfast", "fresh"],
    shortDescription: "Bright ruby grapefruit with a refreshing sweet-bitter finish.",
    longDescription: "Two large ruby grapefruit ideal for breakfast halves, fresh juice, or segmenting into salads and light fruit platters.",
    badges: ["Organic"],
    attributes: { variety: "Ruby Red", count: 2, origin: "Eastern Highlands" },
    sku: "FRT-003",
  },
  {
    id: "p-004",
    slug: "honeydew-melon-slices",
    name: "Honeydew Melon Slices",
    category: "fruits",
    price: 5.2,
    unit: "500 g tray",
    stockQty: 7,
    tags: ["melon", "ready to eat", "chilled", "summer"],
    shortDescription: "Chilled melon slices packed for instant snacking.",
    longDescription: "Fresh-cut honeydew melon in a grab-and-go tray designed for chilled snacking, lunch tables, and quick entertaining.",
    badges: ["Ready to eat"],
    attributes: { packSize: "500 g", prep: "fresh cut", sweetness: "high" },
    sku: "FRT-004",
  },
  {
    id: "p-005",
    slug: "strawberry-punnet-select",
    name: "Strawberry Punnet Select",
    category: "fruits",
    price: 4.95,
    compareAtPrice: 5.4,
    unit: "250 g punnet",
    stockQty: 11,
    featured: true,
    tags: ["berries", "dessert", "fresh", "snacking"],
    shortDescription: "Firm strawberries packed for desserts, yogurt bowls, and snacking.",
    longDescription: "A bright strawberry punnet with dessert-ready berries chosen for color, sweetness, and everyday freshness.",
    badges: ["Featured"],
    attributes: { packSize: "250 g", flavor: "sweet", grade: "Class 1" },
    sku: "FRT-005",
  },
  {
    id: "p-006",
    slug: "banana-family-combo",
    name: "Banana Family Combo",
    category: "fruits",
    price: 6.4,
    unit: "1.5 kg bunch",
    stockQty: 16,
    organic: true,
    tags: ["banana", "smoothie", "school snacks", "family"],
    shortDescription: "A family-size banana bunch for smoothies and lunch boxes.",
    longDescription: "A generous bunch of bananas selected for everyday snacking, cereal bowls, baking, and smoothie prep.",
    badges: ["Organic"],
    attributes: { ripeness: "mixed", weight: "1.5 kg", use: "multi-purpose" },
    sku: "FRT-006",
  },
  {
    id: "p-007",
    slug: "garden-lettuce-crisp-mix",
    name: "Garden Lettuce Crisp Mix",
    category: "vegetables",
    price: 4.2,
    unit: "300 g bag",
    stockQty: 13,
    featured: true,
    organic: true,
    tags: ["salad", "leafy greens", "fresh", "quick meals"],
    shortDescription: "A leafy salad mix for bowls, wraps, and weeknight dinners.",
    longDescription: "A crisp washed mix of green leaves ready for salads, sandwich layering, and healthy everyday meal prep.",
    badges: ["Organic", "Washed"],
    attributes: { packSize: "300 g", prep: "washed", blend: "cos and lollo" },
    sku: "VEG-001",
  },
  {
    id: "p-008",
    slug: "baby-spinach-value-bag",
    name: "Baby Spinach Value Bag",
    category: "vegetables",
    price: 3.9,
    unit: "250 g bag",
    stockQty: 9,
    organic: true,
    tags: ["spinach", "smoothie", "greens", "breakfast"],
    shortDescription: "Tender baby spinach for omelets, smoothies, and sautés.",
    longDescription: "Soft baby spinach leaves with a mild flavor profile for smoothies, omelets, pasta, and weekday green sides.",
    badges: ["Organic"],
    attributes: { packSize: "250 g", prep: "washed", leafSize: "baby" },
    sku: "VEG-002",
  },
  {
    id: "p-009",
    slug: "rainbow-pepper-trio",
    name: "Rainbow Pepper Trio",
    category: "vegetables",
    price: 5.6,
    unit: "3 pack",
    stockQty: 15,
    tags: ["peppers", "stir fry", "salad", "colorful"],
    shortDescription: "Red, yellow, and green peppers for stir-fries and roasts.",
    longDescription: "A trio of sweet peppers with kitchen versatility for salads, pizza toppings, roasting, and colorful weeknight cooking.",
    badges: ["Kitchen staple"],
    attributes: { colors: "red/yellow/green", count: 3, flavor: "sweet" },
    sku: "VEG-003",
  },
  {
    id: "p-010",
    slug: "root-veg-roast-pack",
    name: "Root Veg Roast Pack",
    category: "vegetables",
    price: 7.8,
    unit: "1.8 kg pack",
    stockQty: 8,
    featured: true,
    tags: ["roasting", "carrots", "beetroot", "meal prep"],
    shortDescription: "A roasting mix of carrots, onions, and beetroot.",
    longDescription: "A practical roast pack combining classic root vegetables for oven trays, Sunday lunches, and batch-cooked side dishes.",
    badges: ["Meal prep"],
    attributes: { contents: "carrot/onion/beetroot", weight: "1.8 kg", prep: "whole" },
    sku: "VEG-004",
  },
  {
    id: "p-011",
    slug: "broccoli-floret-tray",
    name: "Broccoli Floret Tray",
    category: "vegetables",
    price: 4.4,
    unit: "400 g tray",
    stockQty: 5,
    tags: ["broccoli", "steam", "healthy", "quick sides"],
    shortDescription: "Trimmed broccoli florets for steaming and stir-frying.",
    longDescription: "A trimmed broccoli tray that moves easily from fridge to pan, supporting healthy lunches and quick vegetable sides.",
    badges: ["Trimmed"],
    attributes: { packSize: "400 g", prep: "trimmed florets", use: "steam or stir fry" },
    sku: "VEG-005",
  },
  {
    id: "p-012",
    slug: "fresh-herb-cooking-duo",
    name: "Fresh Herb Cooking Duo",
    category: "vegetables",
    price: 2.8,
    unit: "2 bunches",
    stockQty: 12,
    tags: ["herbs", "parsley", "coriander", "cooking"],
    shortDescription: "Parsley and coriander bundled for stews, salads, and marinades.",
    longDescription: "A kitchen herb duo chosen for flavor layering in soups, marinades, tomato salads, and everyday finishing touches.",
    badges: ["Fresh bunch"],
    attributes: { herbs: "parsley and coriander", count: 2, freshness: "same-day market" },
    sku: "VEG-006",
  },
  {
    id: "p-013",
    slug: "stoneground-maize-meal",
    name: "Stoneground Maize Meal",
    category: "groceries",
    price: 6.1,
    unit: "2 kg bag",
    stockQty: 20,
    featured: true,
    tags: ["staple", "sadza", "pantry", "family"],
    shortDescription: "A pantry staple for hearty family meals and everyday cooking.",
    longDescription: "Stoneground maize meal milled for a smooth, dependable texture in staple home cooking and family-size meal preparation.",
    badges: ["Staple"],
    attributes: { packSize: "2 kg", grain: "white maize", milling: "stoneground" },
    sku: "GRC-001",
  },
  {
    id: "p-014",
    slug: "premium-basmati-rice",
    name: "Premium Basmati Rice",
    category: "groceries",
    price: 7.3,
    unit: "2 kg bag",
    stockQty: 14,
    tags: ["rice", "pantry", "dinner", "long grain"],
    shortDescription: "Fragrant long-grain basmati rice for weeknight dinners.",
    longDescription: "A fluffy, aromatic basmati rice suited to curries, grilled proteins, and dependable pantry planning.",
    badges: ["Pantry essential"],
    attributes: { grain: "basmati", packSize: "2 kg", cookingTime: "15 min" },
    sku: "GRC-002",
  },
  {
    id: "p-015",
    slug: "cold-pressed-sunflower-oil",
    name: "Cold-Pressed Sunflower Oil",
    category: "groceries",
    price: 5.9,
    unit: "750 ml bottle",
    stockQty: 11,
    tags: ["oil", "cooking", "pantry", "daily use"],
    shortDescription: "A versatile cooking oil for frying, roasting, and salad prep.",
    longDescription: "A light sunflower oil with everyday utility in pan cooking, roasting trays, and household kitchen refills.",
    badges: ["Everyday value"],
    attributes: { size: "750 ml", press: "cold-pressed", use: "multi-purpose cooking" },
    sku: "GRC-003",
  },
  {
    id: "p-016",
    slug: "wholewheat-pasta-pair",
    name: "Wholewheat Pasta Pair",
    category: "groceries",
    price: 4.8,
    unit: "2 x 500 g",
    stockQty: 9,
    organic: true,
    tags: ["pasta", "wholewheat", "healthy pantry", "dinner"],
    shortDescription: "Two pantry-ready pasta packs for quick healthy dinners.",
    longDescription: "A pair of wholewheat pasta packs that balance convenience and pantry depth for quick weeknight meals.",
    badges: ["Organic"],
    attributes: { format: "spaghetti and penne", totalWeight: "1 kg", grain: "wholewheat" },
    sku: "GRC-004",
  },
  {
    id: "p-017",
    slug: "creamy-peanut-butter-jar",
    name: "Creamy Peanut Butter Jar",
    category: "groceries",
    price: 3.75,
    unit: "400 g jar",
    stockQty: 17,
    tags: ["spread", "breakfast", "protein", "pantry"],
    shortDescription: "A smooth peanut butter jar for toast, oats, and snacks.",
    longDescription: "A creamy peanut butter with familiar everyday appeal for sandwiches, baking, and fast breakfast routines.",
    badges: ["Family pantry"],
    attributes: { texture: "smooth", packSize: "400 g", sweetness: "lightly sweetened" },
    sku: "GRC-005",
  },
  {
    id: "p-018",
    slug: "tomato-simmer-sauce-pack",
    name: "Tomato Simmer Sauce Pack",
    category: "groceries",
    price: 4.45,
    unit: "2 x 350 g jars",
    stockQty: 6,
    tags: ["sauce", "pasta night", "pantry", "quick meals"],
    shortDescription: "Two tomato sauces for pasta nights and easy one-pan cooking.",
    longDescription: "A pair of tomato simmer sauces built for fast pasta dinners, meatball pans, and weeknight pantry support.",
    badges: ["Quick meal"],
    attributes: { style: "Italian herb", quantity: 2, jarSize: "350 g" },
    sku: "GRC-006",
  },
  {
    id: "p-019",
    slug: "smoked-turkey-slices",
    name: "Smoked Turkey Slices",
    category: "deli",
    price: 6.8,
    unit: "250 g pack",
    stockQty: 12,
    featured: true,
    tags: ["deli", "sliced", "sandwich", "ready to eat"],
    shortDescription: "Lean smoked turkey slices for sandwiches and wraps.",
    longDescription: "A ready-to-eat deli pack of smoked turkey slices with clean flavor and practical lunchbox appeal.",
    badges: ["Ready to eat"],
    attributes: { sliced: true, packSize: "250 g", protein: "turkey breast" },
    sku: "DEL-001",
  },
  {
    id: "p-020",
    slug: "garlic-herb-chicken-loaf",
    name: "Garlic Herb Chicken Loaf",
    category: "deli",
    price: 7.9,
    unit: "300 g pack",
    stockQty: 8,
    tags: ["deli", "sliced", "chicken", "lunch"],
    shortDescription: "Herbed chicken loaf sliced for easy sandwiches and platters.",
    longDescription: "A deli chicken loaf with garlic-herb seasoning, ideal for cold platters, rolls, and practical lunch prep.",
    badges: ["Freshly sliced"],
    attributes: { sliced: true, seasoning: "garlic herb", packSize: "300 g" },
    sku: "DEL-002",
  },
  {
    id: "p-021",
    slug: "mature-cheddar-slices",
    name: "Mature Cheddar Slices",
    category: "deli",
    price: 5.5,
    unit: "220 g pack",
    stockQty: 14,
    tags: ["cheese", "deli", "sandwich", "ready to eat"],
    shortDescription: "Sharp cheddar slices for burgers, toasties, and lunch boards.",
    longDescription: "A dependable sliced cheddar pack with mature flavor and easy use across toasties, burgers, and snack platters.",
    badges: ["Ready to eat"],
    attributes: { sliced: true, cheeseType: "cheddar", packSize: "220 g" },
    sku: "DEL-003",
  },
  {
    id: "p-022",
    slug: "pepperoni-platter-pack",
    name: "Pepperoni Platter Pack",
    category: "deli",
    price: 8.2,
    unit: "200 g pack",
    stockQty: 7,
    tags: ["pepperoni", "pizza night", "deli", "platter"],
    shortDescription: "Mildly spiced pepperoni slices for platters and pizzas.",
    longDescription: "A platter-ready pepperoni selection with enough spice for pizza toppings, casual hosting, and snack boards.",
    badges: ["Entertaining pick"],
    attributes: { sliced: true, spice: "mild", packSize: "200 g" },
    sku: "DEL-004",
  },
  {
    id: "p-023",
    slug: "potato-salad-deli-tub",
    name: "Potato Salad Deli Tub",
    category: "deli",
    price: 4.95,
    unit: "400 g tub",
    stockQty: 9,
    tags: ["potato salad", "ready to eat", "side dish", "deli"],
    shortDescription: "Creamy deli potato salad for braais and quick side dishes.",
    longDescription: "A chilled deli-style potato salad with a creamy dressing, built for braais, buffet spreads, and easy side plates.",
    badges: ["Ready to serve"],
    attributes: { readyToEat: true, packSize: "400 g", style: "creamy" },
    sku: "DEL-005",
  },
  {
    id: "p-024",
    slug: "coleslaw-crunch-tub",
    name: "Coleslaw Crunch Tub",
    category: "deli",
    price: 4.35,
    unit: "350 g tub",
    stockQty: 11,
    tags: ["coleslaw", "ready to eat", "salad", "deli"],
    shortDescription: "A crunchy deli coleslaw for burgers, braais, and lunch plates.",
    longDescription: "A chilled slaw with fresh crunch and creamy balance that pairs well with braais, fried chicken, and family lunches.",
    badges: ["Ready to serve"],
    attributes: { readyToEat: true, packSize: "350 g", texture: "crunchy" },
    sku: "DEL-006",
  },
  {
    id: "p-025",
    slug: "roast-beef-sandwich-stack",
    name: "Roast Beef Sandwich Stack",
    category: "deli",
    price: 9.4,
    unit: "280 g pack",
    stockQty: 4,
    featured: true,
    tags: ["roast beef", "deli", "ready to eat", "sandwich"],
    shortDescription: "Tender roast beef slices stacked for premium sandwiches.",
    longDescription: "A premium deli roast beef pack prepared for higher-end sandwich builds, wraps, and office lunch routines.",
    badges: ["Chef's pick"],
    attributes: { sliced: true, packSize: "280 g", style: "ready to eat" },
    sku: "DEL-007",
  },
  {
    id: "p-026",
    slug: "gourmet-antipasto-plate",
    name: "Gourmet Antipasto Plate",
    category: "deli",
    price: 12.9,
    unit: "420 g tray",
    stockQty: 5,
    tags: ["antipasto", "hosting", "ready to eat", "platter"],
    shortDescription: "A mixed deli tray for casual hosting and Friday grazing.",
    longDescription: "A composed deli tray with cured meats, cheese, and savory bites for entertaining and elevated snack moments.",
    badges: ["Entertaining"],
    attributes: { readyToEat: true, packSize: "420 g", assortment: "mixed meats and cheese" },
    sku: "DEL-008",
  },
  {
    id: "p-027",
    slug: "sea-salt-chocolate-block",
    name: "Sea Salt Chocolate Block",
    category: "confectionery",
    price: 3.95,
    unit: "90 g bar",
    stockQty: 15,
    featured: true,
    tags: ["chocolate", "dark", "treat", "sea salt"],
    shortDescription: "Dark chocolate with sea salt flakes for a richer treat.",
    longDescription: "A premium chocolate bar with deep cocoa notes and a clean sea-salt finish for after-dinner snacking.",
    badges: ["Premium"],
    attributes: { flavor: "dark chocolate and sea salt", treatType: "bar", cocoa: "70%" },
    sku: "CNF-001",
  },
  {
    id: "p-028",
    slug: "vanilla-shortbread-tin",
    name: "Vanilla Shortbread Tin",
    category: "confectionery",
    price: 6.5,
    unit: "280 g tin",
    stockQty: 12,
    tags: ["biscuits", "vanilla", "tea time", "giftable"],
    shortDescription: "Buttery shortbread biscuits packed in a reusable tin.",
    longDescription: "A tea-time favorite with buttery vanilla shortbread rounds presented in a reusable tin for gifting and pantry indulgence.",
    badges: ["Giftable"],
    attributes: { flavor: "vanilla butter", treatType: "biscuit", packStyle: "tin" },
    sku: "CNF-002",
  },
  {
    id: "p-029",
    slug: "caramel-popcorn-crunch",
    name: "Caramel Popcorn Crunch",
    category: "confectionery",
    price: 4.8,
    unit: "180 g bag",
    stockQty: 10,
    tags: ["popcorn", "caramel", "movie night", "snack"],
    shortDescription: "Crunchy caramel popcorn for movie nights and sharing bowls.",
    longDescription: "A sweet popcorn snack with glossy caramel coating and a crunchy finish suited to family movie nights and weekend snacking.",
    badges: ["Sharing pack"],
    attributes: { flavor: "caramel", treatType: "popcorn", texture: "crunchy" },
    sku: "CNF-003",
  },
  {
    id: "p-030",
    slug: "berry-chew-fruit-sweets",
    name: "Berry Chew Fruit Sweets",
    category: "confectionery",
    price: 2.65,
    unit: "150 g bag",
    stockQty: 21,
    tags: ["sweets", "berry", "chewy", "treat"],
    shortDescription: "Mixed berry chewy sweets for lunch boxes and sweet cravings.",
    longDescription: "A playful fruit-sweet bag filled with berry-flavored chews for casual snacking, desk drawers, and family treats.",
    badges: ["Family favorite"],
    attributes: { flavor: "mixed berry", treatType: "chewy sweets", format: "bag" },
    sku: "CNF-004",
  },
  {
    id: "p-031",
    slug: "hazelnut-praline-truffles",
    name: "Hazelnut Praline Truffles",
    category: "confectionery",
    price: 8.75,
    unit: "160 g box",
    stockQty: 6,
    featured: true,
    tags: ["truffles", "hazelnut", "gift", "premium"],
    shortDescription: "Soft praline truffles with a toasted hazelnut center.",
    longDescription: "A premium confectionery box with soft truffles and hazelnut praline centers for gifting or elevated after-dinner treats.",
    badges: ["Premium", "Giftable"],
    attributes: { flavor: "hazelnut praline", treatType: "truffle", count: 12 },
    sku: "CNF-005",
  },
  {
    id: "p-032",
    slug: "double-choc-cookie-pack",
    name: "Double Choc Cookie Pack",
    category: "confectionery",
    price: 5.1,
    unit: "8 cookies",
    stockQty: 9,
    tags: ["cookies", "chocolate", "tea time", "bakery style"],
    shortDescription: "Bakery-style chocolate cookies with a soft center.",
    longDescription: "A bakery-style cookie pack with rich cocoa flavor and a softer bite, designed for tea breaks and office sharing.",
    badges: ["Bakery style"],
    attributes: { flavor: "double chocolate", treatType: "cookie", count: 8 },
    sku: "CNF-006",
  },
  {
    id: "p-033",
    slug: "coconut-marshmallow-bites",
    name: "Coconut Marshmallow Bites",
    category: "confectionery",
    price: 3.4,
    unit: "140 g tray",
    stockQty: 14,
    tags: ["marshmallow", "coconut", "soft treat", "snack"],
    shortDescription: "Soft marshmallow bites dusted with coconut flakes.",
    longDescription: "A nostalgic sweet tray of vanilla marshmallow bites with coconut coating and soft bite appeal.",
    badges: ["Soft treat"],
    attributes: { flavor: "vanilla coconut", treatType: "marshmallow", format: "tray" },
    sku: "CNF-007",
  },
  {
    id: "p-034",
    slug: "mint-crisp-chocolate-share",
    name: "Mint Crisp Chocolate Share",
    category: "confectionery",
    price: 4.6,
    unit: "120 g bag",
    stockQty: 8,
    tags: ["chocolate", "mint", "sharing", "sweet"],
    shortDescription: "Crisp mint chocolate bites for sharing and dessert tables.",
    longDescription: "A bag of mint chocolate pieces with crisp centers, suited to sharing bowls and sweet end-of-day snacking.",
    badges: ["Sharing pack"],
    attributes: { flavor: "mint chocolate", treatType: "bite-sized", texture: "crisp" },
    sku: "CNF-008",
  },
  {
    id: "p-035",
    slug: "grass-fed-ribeye-steak",
    name: "Grass-Fed Ribeye Steak",
    category: "butchery",
    price: 14.9,
    unit: "450 g tray",
    stockQty: 8,
    featured: true,
    tags: ["beef", "steak", "grass-fed", "premium"],
    shortDescription: "Marbled ribeye steak for pan searing and weekend dinners.",
    longDescription: "A premium ribeye tray with generous marbling for high-heat searing, date-night plates, and grill-focused cooking.",
    badges: ["Grass-fed", "Premium cut"],
    attributes: { cut: "ribeye", weight: "450 g", grassFed: true, halal: false },
    sku: "BUT-001",
  },
  {
    id: "p-036",
    slug: "halal-beef-stew-cubes",
    name: "Halal Beef Stew Cubes",
    category: "butchery",
    price: 9.6,
    unit: "600 g pack",
    stockQty: 13,
    tags: ["beef", "halal", "stew", "family cooking"],
    shortDescription: "Tender halal beef cubes for stews, curries, and pot meals.",
    longDescription: "A practical halal beef pack portioned into stew-ready cubes for curries, tomato stews, and slow-cooked family dishes.",
    badges: ["Halal"],
    attributes: { cut: "stew cubes", weight: "600 g", grassFed: false, halal: true },
    sku: "BUT-002",
  },
  {
    id: "p-037",
    slug: "braai-lamb-chops",
    name: "Braai Lamb Chops",
    category: "butchery",
    price: 13.8,
    unit: "500 g tray",
    stockQty: 7,
    featured: true,
    tags: ["lamb", "braai", "weekend", "premium"],
    shortDescription: "Lamb chops trimmed for braais and celebratory dinners.",
    longDescription: "A premium lamb chop tray prepared for outdoor grilling, family braais, and restaurant-style home dinners.",
    badges: ["Braai pick"],
    attributes: { cut: "loin chops", weight: "500 g", grassFed: true, halal: false },
    sku: "BUT-003",
  },
  {
    id: "p-038",
    slug: "skinless-chicken-breast-fillets",
    name: "Skinless Chicken Breast Fillets",
    category: "butchery",
    price: 8.3,
    unit: "700 g tray",
    stockQty: 16,
    tags: ["chicken", "lean", "meal prep", "protein"],
    shortDescription: "Lean chicken breast fillets for grills, wraps, and meal prep.",
    longDescription: "A versatile tray of skinless chicken breasts for weekday cooking, batch prep, and lighter protein-focused meals.",
    badges: ["Lean protein"],
    attributes: { cut: "breast fillet", weight: "700 g", halal: true, grassFed: false },
    sku: "BUT-004",
  },
  {
    id: "p-039",
    slug: "free-range-chicken-thighs",
    name: "Free-Range Chicken Thighs",
    category: "butchery",
    price: 7.4,
    unit: "800 g tray",
    stockQty: 10,
    tags: ["chicken", "free range", "roast", "juicy"],
    shortDescription: "Juicy chicken thighs ideal for roasting and tray bakes.",
    longDescription: "A free-range chicken thigh tray designed for roasting, braising, and flavorful sheet-pan dinners.",
    badges: ["Free range"],
    attributes: { cut: "thighs", weight: "800 g", halal: true, freeRange: true },
    sku: "BUT-005",
  },
  {
    id: "p-040",
    slug: "beef-mince-family-pack",
    name: "Beef Mince Family Pack",
    category: "butchery",
    price: 11.2,
    unit: "1 kg pack",
    stockQty: 15,
    tags: ["mince", "beef", "family meals", "versatile"],
    shortDescription: "A large beef mince pack for burgers, pasta, and meatballs.",
    longDescription: "A family-size mince pack that supports burgers, pasta sauces, meatballs, and a broad range of practical home meals.",
    badges: ["Family value"],
    attributes: { cut: "mince", weight: "1 kg", fatRatio: "85/15", halal: false },
    sku: "BUT-006",
  },
  {
    id: "p-041",
    slug: "boerewors-braai-coil",
    name: "Boerewors Braai Coil",
    category: "butchery",
    price: 10.7,
    unit: "750 g coil",
    stockQty: 11,
    tags: ["boerewors", "braai", "sausage", "weekend"],
    shortDescription: "Traditional boerewors coil for braais and hearty family meals.",
    longDescription: "A flavorful boerewors coil prepared for weekend braais, grill plates, and easy serving at larger family tables.",
    badges: ["Braai favorite"],
    attributes: { cut: "sausage coil", weight: "750 g", seasoning: "traditional", halal: false },
    sku: "BUT-007",
  },
  {
    id: "p-042",
    slug: "pepper-crusted-pork-chops",
    name: "Pepper-Crusted Pork Chops",
    category: "butchery",
    price: 9.9,
    unit: "650 g tray",
    stockQty: 5,
    tags: ["pork", "pepper", "grill", "butchery"],
    shortDescription: "Seasoned pork chops with cracked pepper for easy grilling.",
    longDescription: "A seasoned pork chop tray with cracked pepper crust, built for skillet cooking, grilling, and practical dinner prep.",
    badges: ["Pre-seasoned"],
    attributes: { cut: "loin chops", weight: "650 g", seasoning: "cracked pepper", halal: false },
    sku: "BUT-008",
  },
  {
    id: "p-043",
    slug: "cape-merlot-reserve",
    name: "Cape Merlot Reserve",
    category: "winery",
    price: 18.9,
    unit: "750 ml bottle",
    stockQty: 10,
    featured: true,
    tags: ["wine", "red", "dinner", "merlot"],
    shortDescription: "A smooth red wine with plum notes and easy dinner pairing.",
    longDescription: "A medium-bodied merlot with dark fruit character and a relaxed finish, suited to pasta, roast chicken, and cheese boards.",
    badges: ["Cellar pick"],
    ageRestricted: true,
    attributes: { bottleSize: "750 ml", variety: "Merlot", style: "red", vintage: 2022 },
    sku: "WIN-001",
  },
  {
    id: "p-044",
    slug: "stellenbosch-cabernet",
    name: "Stellenbosch Cabernet",
    category: "winery",
    price: 22.4,
    unit: "750 ml bottle",
    stockQty: 7,
    tags: ["wine", "cabernet", "red", "steak night"],
    shortDescription: "A fuller-bodied cabernet for steaks and richer dinner menus.",
    longDescription: "A structured cabernet with blackberry notes and deeper body, paired well with steaks, chops, and slow-cooked mains.",
    badges: ["Dinner table"],
    ageRestricted: true,
    attributes: { bottleSize: "750 ml", variety: "Cabernet Sauvignon", style: "red", vintage: 2021 },
    sku: "WIN-002",
  },
  {
    id: "p-045",
    slug: "sunny-chenin-blanc",
    name: "Sunny Chenin Blanc",
    category: "winery",
    price: 16.3,
    unit: "750 ml bottle",
    stockQty: 13,
    tags: ["wine", "white", "chenin", "seafood"],
    shortDescription: "A bright white wine with citrus notes and crisp acidity.",
    longDescription: "A fresh chenin blanc with bright citrus notes and a clean finish, ideal for fish, salads, and warm-weather entertaining.",
    badges: ["Fresh pick"],
    ageRestricted: true,
    attributes: { bottleSize: "750 ml", variety: "Chenin Blanc", style: "white", vintage: 2023 },
    sku: "WIN-003",
  },
  {
    id: "p-046",
    slug: "garden-sauvignon-blanc",
    name: "Garden Sauvignon Blanc",
    category: "winery",
    price: 17.2,
    unit: "750 ml bottle",
    stockQty: 8,
    tags: ["wine", "white", "sauvignon blanc", "crisp"],
    shortDescription: "A crisp sauvignon blanc for salads, sushi, and light dinners.",
    longDescription: "A lively sauvignon blanc with green citrus tones and brisk acidity that suits lighter meals and easy hosting.",
    badges: ["Crisp style"],
    ageRestricted: true,
    attributes: { bottleSize: "750 ml", variety: "Sauvignon Blanc", style: "white", vintage: 2023 },
    sku: "WIN-004",
  },
  {
    id: "p-047",
    slug: "rose-picnic-bottle",
    name: "Rosé Picnic Bottle",
    category: "winery",
    price: 15.5,
    unit: "750 ml bottle",
    stockQty: 9,
    tags: ["wine", "rose", "picnic", "summer"],
    shortDescription: "A chilled rosé with berry notes and an easy-going finish.",
    longDescription: "A dry rosé with strawberry notes and relaxed freshness, designed for picnics, light lunches, and casual gatherings.",
    badges: ["Summer favorite"],
    ageRestricted: true,
    attributes: { bottleSize: "750 ml", variety: "Rosé Blend", style: "rosé", vintage: 2023 },
    sku: "WIN-005",
  },
  {
    id: "p-048",
    slug: "sparkling-brut-classic",
    name: "Sparkling Brut Classic",
    category: "winery",
    price: 24.8,
    unit: "750 ml bottle",
    stockQty: 5,
    featured: true,
    tags: ["wine", "sparkling", "celebration", "brut"],
    shortDescription: "A celebratory brut with fine bubbles and citrus lift.",
    longDescription: "A sparkling brut with brisk citrus structure and fine mousse for celebrations, hosting, and milestone dinners.",
    badges: ["Celebration"],
    ageRestricted: true,
    attributes: { bottleSize: "750 ml", variety: "Brut", style: "sparkling", vintage: 2021 },
    sku: "WIN-006",
  },
  {
    id: "p-049",
    slug: "sweet-moscato-chill",
    name: "Sweet Moscato Chill",
    category: "winery",
    price: 14.2,
    unit: "750 ml bottle",
    stockQty: 12,
    tags: ["wine", "moscato", "sweet", "dessert"],
    shortDescription: "A lightly sweet chilled wine for desserts and relaxed evenings.",
    longDescription: "A fragrant moscato with soft sweetness and approachable style, suited to fruit desserts and relaxed social evenings.",
    badges: ["Easy drinking"],
    ageRestricted: true,
    attributes: { bottleSize: "750 ml", variety: "Moscato", style: "sweet white", vintage: 2024 },
    sku: "WIN-007",
  },
  {
    id: "p-050",
    slug: "mini-prosecco-pair",
    name: "Mini Prosecco Pair",
    category: "winery",
    price: 13.6,
    unit: "2 x 200 ml",
    stockQty: 6,
    tags: ["wine", "prosecco", "mini bottles", "sparkling"],
    shortDescription: "Two mini sparkling bottles for gifting and smaller celebrations.",
    longDescription: "A pair of mini sparkling wine bottles with convenient portioning for gifting, picnics, and intimate celebrations.",
    badges: ["Giftable"],
    ageRestricted: true,
    attributes: { bottleSize: "2 x 200 ml", variety: "Prosecco", style: "sparkling", serving: "mini bottles" },
    sku: "WIN-008",
  },
  {
    id: "p-051",
    slug: "farmhouse-full-cream-milk",
    name: "Farmhouse Full Cream Milk",
    category: "dairy-eggs",
    price: 2.25,
    unit: "2 L bottle",
    stockQty: 18,
    tags: ["milk", "breakfast", "dairy", "family"],
    shortDescription: "Full cream milk for cereal, tea, cooking, and family breakfasts.",
    longDescription: "A dependable household milk bottle with everyday utility across cereal bowls, tea rounds, baking, and cooking.",
    badges: ["Household staple"],
    attributes: { fatContent: "full cream", size: "2 L", storage: "chilled" },
    sku: "DAI-001",
  },
  {
    id: "p-052",
    slug: "free-range-eggs-dozen",
    name: "Free-Range Eggs Dozen",
    category: "dairy-eggs",
    price: 3.8,
    unit: "12 eggs",
    stockQty: 20,
    organic: true,
    tags: ["eggs", "breakfast", "baking", "free range"],
    shortDescription: "A dozen free-range eggs for breakfasts and baking.",
    longDescription: "A tray of free-range eggs with dependable kitchen utility for omelets, baking, and family breakfast prep.",
    badges: ["Free range"],
    attributes: { count: 12, farming: "free range", size: "large" },
    sku: "DAI-002",
  },
  {
    id: "p-053",
    slug: "plain-greek-yogurt-tub",
    name: "Plain Greek Yogurt Tub",
    category: "dairy-eggs",
    price: 4.7,
    unit: "500 g tub",
    stockQty: 9,
    tags: ["yogurt", "breakfast", "protein", "dairy"],
    shortDescription: "Thick Greek yogurt for breakfast bowls and sauces.",
    longDescription: "A creamy Greek yogurt tub with breakfast, snack, and sauce versatility for a more premium dairy staple.",
    badges: ["Protein rich"],
    attributes: { style: "Greek", packSize: "500 g", flavor: "plain" },
    sku: "DAI-003",
  },
  {
    id: "p-054",
    slug: "salted-butter-brick",
    name: "Salted Butter Brick",
    category: "dairy-eggs",
    price: 3.4,
    unit: "500 g block",
    stockQty: 7,
    tags: ["butter", "baking", "breakfast", "dairy"],
    shortDescription: "Salted butter for toast, baking, and everyday cooking.",
    longDescription: "A practical butter block suited to baking, breakfast tables, pan cooking, and household fridge staples.",
    badges: ["Baking essential"],
    attributes: { salted: true, packSize: "500 g", format: "block" },
    sku: "DAI-004",
  },
  {
    id: "p-055",
    slug: "mozzarella-cooking-shreds",
    name: "Mozzarella Cooking Shreds",
    category: "dairy-eggs",
    price: 4.95,
    unit: "300 g bag",
    stockQty: 8,
    tags: ["cheese", "pizza night", "mozzarella", "dairy"],
    shortDescription: "Shredded mozzarella for pizza, pasta bakes, and toasties.",
    longDescription: "A melt-friendly mozzarella bag designed for pizza night, baked dishes, and quick cheese layering in family cooking.",
    badges: ["Melts well"],
    attributes: { cheeseType: "mozzarella", packSize: "300 g", format: "shredded" },
    sku: "DAI-005",
  },
  {
    id: "p-056",
    slug: "breakfast-orange-juice",
    name: "Breakfast Orange Juice",
    category: "beverages",
    price: 3.6,
    unit: "1.5 L carton",
    stockQty: 12,
    featured: true,
    tags: ["juice", "breakfast", "citrus", "family"],
    shortDescription: "A breakfast orange juice carton for family tables and brunches.",
    longDescription: "A family-friendly orange juice carton for breakfast pours, brunches, and fridge-ready refreshment.",
    badges: ["Breakfast pick"],
    attributes: { flavor: "orange", size: "1.5 L", style: "juice" },
    sku: "BEV-001",
  },
  {
    id: "p-057",
    slug: "sparkling-water-lime-case",
    name: "Sparkling Water Lime Case",
    category: "beverages",
    price: 5.8,
    unit: "6 x 330 ml",
    stockQty: 16,
    tags: ["sparkling water", "lime", "refreshment", "zero sugar"],
    shortDescription: "Lime sparkling water cans for chilled low-sugar refreshment.",
    longDescription: "A case of lightly flavored sparkling water that keeps the fridge stocked with crisp, no-sugar refreshment.",
    badges: ["Zero sugar"],
    attributes: { flavor: "lime", format: "can", quantity: 6 },
    sku: "BEV-002",
  },
  {
    id: "p-058",
    slug: "rooibos-tea-selection",
    name: "Rooibos Tea Selection",
    category: "beverages",
    price: 3.2,
    unit: "40 tea bags",
    stockQty: 18,
    tags: ["tea", "rooibos", "hot drinks", "pantry"],
    shortDescription: "A rooibos tea box for morning mugs and evening wind-downs.",
    longDescription: "A warming rooibos tea box with all-day drinkability and strong pantry value for households and offices.",
    badges: ["Pantry essential"],
    attributes: { teaType: "rooibos", count: 40, caffeine: false },
    sku: "BEV-003",
  },
  {
    id: "p-059",
    slug: "house-blend-ground-coffee",
    name: "House Blend Ground Coffee",
    category: "beverages",
    price: 6.9,
    unit: "250 g bag",
    stockQty: 9,
    tags: ["coffee", "ground", "morning", "beverages"],
    shortDescription: "A balanced ground coffee for everyday home brewing.",
    longDescription: "A medium-roast house blend with smooth body and dependable flavor for daily filter coffee and French press brewing.",
    badges: ["Medium roast"],
    attributes: { roast: "medium", format: "ground", packSize: "250 g" },
    sku: "BEV-004",
  },
  {
    id: "p-060",
    slug: "ginger-beer-party-pack",
    name: "Ginger Beer Party Pack",
    category: "beverages",
    price: 7.1,
    unit: "6 x 500 ml",
    stockQty: 11,
    tags: ["soft drinks", "ginger beer", "party pack", "refreshment"],
    shortDescription: "A spicy-sweet ginger beer multipack for gatherings and braais.",
    longDescription: "A larger ginger beer multipack with bold flavor and easy crowd appeal for gatherings, braais, and home refreshment.",
    badges: ["Party pack"],
    attributes: { flavor: "ginger beer", format: "bottle", quantity: 6 },
    sku: "BEV-005",
  },
  {
    id: "p-061",
    slug: "citrus-dishwash-liquid",
    name: "Citrus Dishwash Liquid",
    category: "household",
    price: 2.95,
    unit: "750 ml bottle",
    stockQty: 14,
    tags: ["cleaning", "dishwashing", "kitchen", "household"],
    shortDescription: "A citrus dishwashing liquid for everyday kitchen clean-up.",
    longDescription: "A practical dishwash liquid with citrus scent and strong everyday value for kitchen clean-up and sink-side refills.",
    badges: ["Kitchen essential"],
    attributes: { scent: "citrus", size: "750 ml", use: "dishwashing" },
    sku: "HOU-001",
  },
  {
    id: "p-062",
    slug: "laundry-fresh-powder",
    name: "Laundry Fresh Powder",
    category: "household",
    price: 6.4,
    unit: "2 kg box",
    stockQty: 10,
    tags: ["laundry", "detergent", "household", "cleaning"],
    shortDescription: "A fresh-scent laundry powder for family loads and weekly washing.",
    longDescription: "A family laundry powder box built for routine washing, dependable cleaning, and practical household restocking.",
    badges: ["Value size"],
    attributes: { scent: "fresh linen", size: "2 kg", use: "machine wash" },
    sku: "HOU-002",
  },
  {
    id: "p-063",
    slug: "bathroom-tissue-value-pack",
    name: "Bathroom Tissue Value Pack",
    category: "household",
    price: 5.3,
    unit: "12 rolls",
    stockQty: 19,
    tags: ["tissue", "paper goods", "household", "bulk"],
    shortDescription: "A 12-roll bathroom tissue pack for easy home top-ups.",
    longDescription: "A dependable bathroom tissue value pack that supports everyday stocking and practical household planning.",
    badges: ["Value pack"],
    attributes: { rollCount: 12, ply: 2, format: "pack" },
    sku: "HOU-003",
  },
  {
    id: "p-064",
    slug: "kitchen-surface-wipes",
    name: "Kitchen Surface Wipes",
    category: "household",
    price: 3.75,
    unit: "80 wipes",
    stockQty: 9,
    tags: ["wipes", "kitchen", "cleaning", "household"],
    shortDescription: "Quick-clean antibacterial wipes for counters and handles.",
    longDescription: "A resealable tub of surface wipes suited to quick kitchen reset routines, dining tables, and high-touch areas.",
    badges: ["Quick clean"],
    attributes: { count: 80, use: "surface cleaning", antibacterial: true },
    sku: "HOU-004",
  },
  {
    id: "p-065",
    slug: "bin-liner-home-roll",
    name: "Bin Liner Home Roll",
    category: "household",
    price: 2.6,
    unit: "20 bags",
    stockQty: 13,
    tags: ["bin liners", "household", "cleaning", "kitchen"],
    shortDescription: "Strong household bin liners for daily kitchen and utility use.",
    longDescription: "A roll of durable bin liners designed for routine home use, kitchen waste, and general household clean-up.",
    badges: ["Strong hold"],
    attributes: { count: 20, size: "medium", durability: "heavy duty" },
    sku: "HOU-005",
  },
];

export const products = productSeeds.map((seed, index) => createProduct(seed, index));

export const defaultStockSnapshot: StockSnapshot = Object.fromEntries(
  products.map((product) => [
    product.id,
    {
      quantity: product.stockQty,
      state: product.stockState,
    },
  ]),
);
